import { h } from 'vue'
import { VSvgIcon } from 'vuetify/components/VIcon'
import { aliases } from 'vuetify/iconsets/mdi-svg'
import type { IconProps, IconSet } from 'vuetify'
import {
  mdiAlert,
  mdiAlertCircle,
  mdiAlertCircleOutline,
  mdiAlertOutline,
  mdiArrowDown,
  mdiArrowUp,
  mdiAws,
  mdiBlockHelper,
  mdiBookmarkOutline,
  mdiCancel,
  mdiCheck,
  mdiCheckCircleOutline,
  mdiCheckNetworkOutline,
  mdiChevronDown,
  mdiChevronRight,
  mdiChevronUp,
  mdiClose,
  mdiCogOutline,
  mdiContentCopy,
  mdiContentDuplicate,
  mdiContentSaveOutline,
  mdiDatabase,
  mdiDatabaseOffOutline,
  mdiDatabaseSearch,
  mdiDatabaseSearchOutline,
  mdiDelete,
  mdiDeleteSweepOutline,
  mdiDockBottom,
  mdiDockRight,
  mdiDolphin,
  mdiDotsVertical,
  mdiDownload,
  mdiElephant,
  mdiEye,
  mdiEyeOff,
  mdiFileAlertOutline,
  mdiFileCabinet,
  mdiFileDocumentOutline,
  mdiFileTreeOutline,
  mdiFolderOpenOutline,
  mdiFolderOutline,
  mdiFormatAlignLeft,
  mdiFormatListBulleted,
  mdiFunctionVariant,
  mdiHelpCircleOutline,
  mdiHistory,
  mdiInformationOutline,
  mdiKeyAlertOutline,
  mdiKeyChain,
  mdiKeyVariant,
  mdiLanConnect,
  mdiLanDisconnect,
  mdiLanPending,
  mdiMagnify,
  mdiMicrosoft,
  mdiPencil,
  mdiPin,
  mdiPinOutline,
  mdiPlay,
  mdiPlaylistPlay,
  mdiPlus,
  mdiRefresh,
  mdiScriptTextOutline,
  mdiServer,
  mdiSitemapOutline,
  mdiSortAlphabeticalVariant,
  mdiStop,
  mdiTable,
  mdiTableColumn,
  mdiTableEye,
  mdiTimerAlertOutline,
  mdiTune,
  mdiVariable,
  mdiWeatherNight,
  mdiWeatherSunny,
} from '@mdi/js'

/**
 * The path of each icon the application draws, keyed by the name that the
 * components give. The application holds these paths alone, and not the whole
 * icon font, so the bundle carries the icons it uses and no more. An icon
 * that a component names must stand in this record.
 */
export const iconPaths: Record<string, string> = {
  'mdi-alert': mdiAlert,
  'mdi-alert-circle': mdiAlertCircle,
  'mdi-alert-circle-outline': mdiAlertCircleOutline,
  'mdi-alert-outline': mdiAlertOutline,
  'mdi-arrow-down': mdiArrowDown,
  'mdi-arrow-up': mdiArrowUp,
  'mdi-aws': mdiAws,
  'mdi-block-helper': mdiBlockHelper,
  'mdi-bookmark-outline': mdiBookmarkOutline,
  'mdi-cancel': mdiCancel,
  'mdi-check': mdiCheck,
  'mdi-check-circle-outline': mdiCheckCircleOutline,
  'mdi-check-network-outline': mdiCheckNetworkOutline,
  'mdi-chevron-down': mdiChevronDown,
  'mdi-chevron-right': mdiChevronRight,
  'mdi-chevron-up': mdiChevronUp,
  'mdi-close': mdiClose,
  'mdi-cog-outline': mdiCogOutline,
  'mdi-content-copy': mdiContentCopy,
  'mdi-content-duplicate': mdiContentDuplicate,
  'mdi-content-save-outline': mdiContentSaveOutline,
  'mdi-database': mdiDatabase,
  'mdi-database-off-outline': mdiDatabaseOffOutline,
  'mdi-database-search': mdiDatabaseSearch,
  'mdi-database-search-outline': mdiDatabaseSearchOutline,
  'mdi-delete': mdiDelete,
  'mdi-delete-sweep-outline': mdiDeleteSweepOutline,
  'mdi-dock-bottom': mdiDockBottom,
  'mdi-dock-right': mdiDockRight,
  'mdi-dolphin': mdiDolphin,
  'mdi-dots-vertical': mdiDotsVertical,
  'mdi-download': mdiDownload,
  'mdi-elephant': mdiElephant,
  'mdi-eye': mdiEye,
  'mdi-eye-off': mdiEyeOff,
  'mdi-file-alert-outline': mdiFileAlertOutline,
  'mdi-file-cabinet': mdiFileCabinet,
  'mdi-file-document-outline': mdiFileDocumentOutline,
  'mdi-file-tree-outline': mdiFileTreeOutline,
  'mdi-folder-open-outline': mdiFolderOpenOutline,
  'mdi-folder-outline': mdiFolderOutline,
  'mdi-format-align-left': mdiFormatAlignLeft,
  'mdi-format-list-bulleted': mdiFormatListBulleted,
  'mdi-function-variant': mdiFunctionVariant,
  'mdi-help-circle-outline': mdiHelpCircleOutline,
  'mdi-history': mdiHistory,
  'mdi-information-outline': mdiInformationOutline,
  'mdi-key-alert-outline': mdiKeyAlertOutline,
  'mdi-key-chain': mdiKeyChain,
  'mdi-key-variant': mdiKeyVariant,
  'mdi-lan-connect': mdiLanConnect,
  'mdi-lan-disconnect': mdiLanDisconnect,
  'mdi-lan-pending': mdiLanPending,
  'mdi-magnify': mdiMagnify,
  'mdi-microsoft': mdiMicrosoft,
  'mdi-pencil': mdiPencil,
  'mdi-pin': mdiPin,
  'mdi-pin-outline': mdiPinOutline,
  'mdi-play': mdiPlay,
  'mdi-playlist-play': mdiPlaylistPlay,
  'mdi-plus': mdiPlus,
  'mdi-refresh': mdiRefresh,
  'mdi-script-text-outline': mdiScriptTextOutline,
  'mdi-server': mdiServer,
  'mdi-sitemap-outline': mdiSitemapOutline,
  'mdi-sort-alphabetical-variant': mdiSortAlphabeticalVariant,
  'mdi-stop': mdiStop,
  'mdi-table': mdiTable,
  'mdi-table-column': mdiTableColumn,
  'mdi-table-eye': mdiTableEye,
  'mdi-timer-alert-outline': mdiTimerAlertOutline,
  'mdi-tune': mdiTune,
  'mdi-variable': mdiVariable,
  'mdi-weather-night': mdiWeatherNight,
  'mdi-weather-sunny': mdiWeatherSunny,
}

/**
 * The path of one icon. A name that this record does not hold, and the path
 * of an alias of Vuetify, come back as they arrived.
 */
export function pathFor(icon: IconProps['icon']): IconProps['icon'] {
  if (typeof icon !== 'string') {
    return icon
  }
  return iconPaths[icon] ?? icon
}

/** The icon set that draws a name of Material Design Icons as a path. */
export const mdi: IconSet = {
  component: (props: IconProps) => h(VSvgIcon, { ...props, icon: pathFor(props.icon) }),
}

export { aliases }
