title: SQL Explorer
description: An open source SQL client for Mac, Windows and Linux. An SSMS alternative for MS SQL Server, AWS Athena, PostgreSQL, MySQL, MariaDB and SQLite.
url: https://sql-explorer.tbmh.org
lang: en-US
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
author: Christopher Wetherill
logo: /assets/icon.png
defaults:
  - scope:
      path: ""
    values:
      layout: default
      image:
        path: /assets/social-card.png
        width: 1280
        height: 640
        alt: SQL Explorer, an open source SQL client for macOS, Windows and Linux
  - scope:
      path: "guide"
    values:
      layout: guide
